Document: mingw-w64-libffi
Title: Debian mingw-w64-libffi Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-libffi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-libffi/mingw-w64-libffi.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-libffi/mingw-w64-libffi.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-libffi/mingw-w64-libffi.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-libffi/html/index.html
Files: /usr/share/doc/mingw-w64-libffi/html/*.html
